-- 1. Create the Online table
CREATE TABLE IF NOT EXISTS public."Online" (
    online_id bigint generated by default as identity primary key,
    facebook_link text,
    instagram_link text,
    tiktok_link text,
    website_link text,
    additional_link text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone,
    brand_id bigint references public."Brand"(brand_id) ON DELETE CASCADE
);

-- 2. Add product_gender to Products table (if it doesn't already exist)
ALTER TABLE public."Products" ADD COLUMN IF NOT EXISTS product_gender text;

-- 3. Add price_range to Brand table
-- Values: '$' = RM0-50.99, '$$' = RM51-99.99, '$$$' = RM100+
ALTER TABLE public."Brand" ADD COLUMN IF NOT EXISTS price_range text
  CHECK (price_range IN ('$', '$$', '$$$'));

-- 3. (Optional) Make sure RLS for Online table allows public read, and auth write
-- You can set this up via the Supabase Dashboard directly, or run:
ALTER TABLE public."Online" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public."Online" FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public."Online" FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users only" ON public."Online" FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users only" ON public."Online" FOR DELETE USING (auth.role() = 'authenticated');

-- Also, check if "Products" needs similar RLS rules if not already set.
